const fs = require('node:fs')
const path = require('node:path')
const parser = require('@babel/parser')
const traverse = require('@babel/traverse').default

const root = path.resolve(__dirname, '..')
// algorithms.js 现在只承载 CATEGORIES + 聚合器；具体算法住在 algorithms/<subject>.js
// 这里枚举：主文件（CATEGORIES 源）+ algorithms/ 子目录所有 .js + 独立的 extraAlgorithms.js
const algorithmsDir = path.join(root, 'src/data/algorithms')
const subjectFiles = fs.readdirSync(algorithmsDir)
  .filter(f => f.endsWith('.js'))
  .map(f => path.posix.join('src/data/algorithms', f))
const sourceFiles = [
  'src/data/algorithms.js',
  ...subjectFiles.sort(),
  'src/data/extraAlgorithms.js',
]

const metaFields = new Set([
  'slug',
  'name',
  'nameEn',
  'category',
  'difficulty',
  'viz',
  'timeComplexity',
  'spaceComplexity',
  'stable',
  'inPlace',
  'description',
])

function keyName(node) {
  if (!node) return null
  if (node.type === 'Identifier') return node.name
  if (node.type === 'StringLiteral' || node.type === 'NumericLiteral') return String(node.value)
  return null
}

function simpleValue(node) {
  if (!node) return undefined
  if (node.type === 'StringLiteral' || node.type === 'BooleanLiteral' || node.type === 'NumericLiteral') return node.value
  if (node.type === 'NullLiteral') return null
  if (node.type === 'ObjectExpression') {
    const out = {}
    for (const prop of node.properties) {
      if (prop.type !== 'ObjectProperty') return undefined
      const key = keyName(prop.key)
      const value = simpleValue(prop.value)
      if (!key || value === undefined) return undefined
      out[key] = value
    }
    return out
  }
  return undefined
}

function objectHasSlug(node) {
  return node.properties?.some(prop =>
    prop.type === 'ObjectProperty' &&
    keyName(prop.key) === 'slug' &&
    prop.value.type === 'StringLiteral'
  )
}

function parseFile(file) {
  const source = fs.readFileSync(path.join(root, file), 'utf8')
  return parser.parse(source, { sourceType: 'module', plugins: ['jsx'] })
}

function extractCategories(ast) {
  let categories = null
  traverse(ast, {
    VariableDeclarator(p) {
      if (p.node.id.type === 'Identifier' && p.node.id.name === 'CATEGORIES' && p.node.init?.type === 'ObjectExpression') {
        categories = simpleValue(p.node.init)
      }
    },
  })
  return categories
}

function extractAlgorithmMeta(ast) {
  const records = []
  traverse(ast, {
    ObjectExpression(p) {
      if (!objectHasSlug(p.node)) return
      const record = {}
      for (const prop of p.node.properties) {
        if (prop.type !== 'ObjectProperty') continue
        const key = keyName(prop.key)
        if (!metaFields.has(key)) continue
        const value = simpleValue(prop.value)
        if (value !== undefined) record[key] = value
      }
      if (record.slug && record.name && record.category) records.push(record)
    },
  })
  return records
}

const asts = sourceFiles.map(file => [file, parseFile(file)])
const categories = extractCategories(asts[0][1])
const seen = new Set()
const algorithms = asts
  .flatMap(([, ast]) => extractAlgorithmMeta(ast))
  .filter(algo => {
    if (seen.has(algo.slug)) return false
    seen.add(algo.slug)
    return true
  })

const output = `// Generated by scripts/generateAlgorithmMeta.cjs.
// Keep this module free of algorithm functions, long prose, and code samples.

export const CATEGORIES = ${JSON.stringify(categories, null, 2)}

export const ALGORITHM_LIST = ${JSON.stringify(algorithms, null, 2)}

export const ALGORITHMS = Object.fromEntries(ALGORITHM_LIST.map(algo => [algo.slug, algo]))

export function getAlgorithmsByCategory(catKey) {
  return ALGORITHM_LIST.filter(algo => algo.category === catKey)
}

export function getAlgorithmMeta(slug) {
  return ALGORITHMS[slug] || null
}
`

fs.writeFileSync(path.join(root, 'src/data/algorithmMeta.js'), output)
console.log(`Generated ${algorithms.length} algorithm metadata records.`)
